### ISSUE TITLE
最新格式会死循环

### ISSUE THREAD

**Issue by unruledboy** [JadynWong/IP_qqwry#1]
ConsoleApp1\MyIpSearch.cs, 410行-414行。

当文件无法正确下载的时候，会出现这个问题，如果从纯真网站直接下载文件便可以了。

**Comment by JadynWong** [comment]
更新时候写入文件有bug  ，已经更新写入方式 ，我这边测试可以了，你可以再试下

**Comment by unruledboy** [comment]
可以了，谢谢
