### ISSUE TITLE
数据库在哪下载

### ISSUE THREAD

**Issue by parabeyond008** [JadynWong/IP_qqwry#25]
qqwry.dat，我下载的运行报错：Unhandled exception. System.Exception: -2 sign error
不知道在哪下载正确的数据库

**Comment by JadynWong** [comment]
https://cz88.net/geo-public

纯真社区版IP库已经禁止商业用途

v20230524 https://www.cz88.net/soft/y41keyK-2023-05-24.zip

下载安装后安装目录提取qqwry.dat
